[contract]

name = "Sai tub"
version = "1.0"
desc = "Multi-collateral Dai"
abi = "abi/tub.json"

[contract.address]

kovan = "0xa6bfc88aa5a5981a958f9bcb885fcb3db0bf941e"
mainnet = "0x448a5065aebb8e423f0896e6c5d525c040f59af3"

[[contract.events]]

sig = "LogNewCup(address lad, bytes32 cup)"
actions = ["db/cup-new.sql"]

[[contract.events]]

sig = "LogNote(bytes4 sig, address guy, bytes32 foo, bytes32 bar, uint wad, bytes fax)"
topics = ["0x01", "0x02"]
actions = ["db/cup-action.sql"]
data = "tub/cup.go"

[[contract.events]]

sig = "@newBlock"
actions = ["db/block-new.sql"]
data = "tub/prices.go"

[psql]

schema = "db/schema.sql"

[psql.migrations]

1 = "db/migrate/tables.sql"
2 = "db/migrate/queries.sql"
