[contract]

name = "Flopper"
version = "0.1-unstable"
lib = "rainbreak/fuss"
abi = "../abi/flop.json"

[contract.address]

mainnet = ???

[[contract.events]]

sig = "Kick(
  uint id,
  uint bid,
  uint lot,
  address guy,
  address gal,
  address tit,
  address tat,
  uint48 end,
  address mom,
)"
actions = ["../db/bid-kick.sql"]

[[contract.events]]

sig = "Tend(
  uint id,
  address mom,
  address guy,
  uint lot,
  uint bid,
  uint48 tic
)"
actions = ["../db/bid-tend.sql"]

[[contract.events]]

sig = "Deal(uint id)"
actions = ["../db/bid-deal.sql"]

[psql]

schema = "db/schema.sql"

[psql.migrations]

1 = "db/migrate/tables.sql"
2 = "db/migrate/queries.sql"
