[contract]

name = "Pip Medianizer"
version = "1.0"
lib = "makerdao/medianizer"

[contract.address]

mainnet = "0x729D19f657BD0614b4985Cf1D82531c67569197B"

[[contract.events]]

sig = "LogNote(bytes4 sig, address guy, bytes32 foo, bytes32 bar, uint wad, bytes fax)"
actions = ["db/poke.sql"]

[psql]

schema = "db/schema.sql"

[psql.migrations]

1 = "db/migrate/tables.sql"
