[contract]

name = "Dai bin"
version = "1.0"
desc = "Multi-collateral Dai"
address = {ethlive = "0x01", kovan = "0x02"}
abi = "abi/bin.json"

[[contract.events]]

sig = "Form(ilk uint256)"
actions = ["db/insertIlk.sql"]
data = "lib/getState.go"

[psql]

schema = "db/schema.sql"

[psql.migrations]

1 = "db/migrate/tables.sql"
2 = "db/migrate/views.sql"
