[contract]

name = "Dai bin"
version = "1.0"
lib = rainbreak/coins
abi = "abi/bin.json"

[contract.address]

mainnet = ???

[[contract.events]]

sig = "Form(uint256 id, address gem)"
actions = ["db/form.sql"]

[[contract.events]]

sig = "Fuss(bytes32 ilk, address flip)"
actions = ["db/fuss.sql"]

[[contract.events]]

sig = "File(bytes32 id, uint spot, uint rate, uint line)"
actions = ["db/file.sql"]

[[contract.events]]

sig = "Frob(bytes32 id, address guy, uint ink, uint art)"
actions = ["db/frob.sql"]

[psql]

schema = "db/schema.sql"

[psql.migrations]

1 = "db/migrate/tables.sql"
2 = "db/migrate/queries.sql"
